#!/bin/sh
# echo Setting permissions ...
# ./fix-permissions.sh Bibliotek
# echo Uploading to uio.no ...
rsync -avz --progress --delete --progress --modify-window=2 ~/Google\ Drive/Calibre\ Library /Volumes/Download
# echo Uploading to hekta.org ...
# rsync -avz --delete Bibliotek/ vegardoy@hekta.org:public_html/temp/books
